import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Set;

/**
 * Created by Shakib on 7/5/2016.
 *
 * This class is a template for an asset (also referred to as a file), specifically an asset that will be inserted
 * in the Assets table in DynamoDB. Special annotations are used to utilize the DynamoDB wrapper, which specify the
 * table name, the primary key, and the rest of the attributes in the table.
 */

@DynamoDBTable(tableName = "DALN-Assets")
public class Asset
{
    private String assetId;
    private String postId;
    private String assetType;
    private String assetLocation;
    private String dalnId;

    @DynamoDBHashKey(attributeName = "AssetId")
    @DynamoDBAutoGeneratedKey
    public String getAssetId() {return assetId;}
    public void setAssetId(String assetId) {this.assetId = assetId;}

    @DynamoDBAttribute(attributeName = "PostId")
    public String getPostId() {return postId;}
    public void setPostId(String postId) {this.postId = postId;}

    @DynamoDBAttribute(attributeName = "AssetType")
    public String getAssetType() {return assetType;}
    public void setAssetType(String assetType) {this.assetType = assetType;}

    @DynamoDBAttribute(attributeName = "AssetLocation")
    public String getAssetLocation() {return assetLocation;}
    public void setAssetLocation(String assetLocation) {this.assetLocation = assetLocation;}

    @DynamoDBAttribute(attributeName = "DalnId")
    public String getDalnId() {return dalnId;}
    public void setDalnId(String dalnId) {this.dalnId = dalnId;}

}

