import java.util.*;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

/**
 * Created by Shakib on 7/5/2016.
 *
 * This class is a template for a post, specifically a post that will be inserted in the Posts
 * table in DynamoDB. Special annotations are used to utilize the DynamoDB wrapper, which specify the
 * table name, the primary key, and the rest of the attributes in the table.
 */

@DynamoDBTable(tableName = "DALN-Posts")
public class Post
{
    private String postId, title, description, identifierUri, dateAccessioned,
    dateAvailable, dateCreated, dateIssued, rightsConsent, rightsRelease;
    private List<String> contributorAuthor, contributorInterviewer, creatorGender,
    creatorRaceEthnicity, creatorClass, creatorYearOfBirth, coverageSpatial,
    coveragePeriod, coverageRegion, coverageStateProvince, coverageNationality,
    language,subject;
    private List<HashMap<String,String>> assetList;
    private String dalnId;

    @DynamoDBHashKey(attributeName = "PostId")
    @DynamoDBAutoGeneratedKey
    public String getPostId() {return postId;}
    public void setPostId(String postId) {this.postId = postId;}

    @DynamoDBAttribute(attributeName = "dalnId")
    public String getDalnId() {return dalnId;}
    public void setDalnId(String dalnId) {this.dalnId = dalnId;}

    @DynamoDBAttribute(attributeName = "title")
    public String getTitle() {return title;}
    public void setTitle(String title) {this.title = title;}

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {return description;}
    public void setDescription(String description) {this.description = description;}

    @DynamoDBAttribute(attributeName = "identifierUri")
    public String getIdentifierUri() {return identifierUri;}
    public void setIdentifierUri(String identifierUri) {this.identifierUri = identifierUri;}

    @DynamoDBAttribute(attributeName = "dateAccessioned")
    public String getDateAccessioned() {return dateAccessioned;}
    public void setDateAccessioned(String dateAccessioned) {this.dateAccessioned = dateAccessioned;}

    @DynamoDBAttribute(attributeName = "dateAvailable")
    public String getDateAvailable() {return dateAvailable;}
    public void setDateAvailable(String dateAvailable) {this.dateAvailable = dateAvailable;}

    @DynamoDBAttribute(attributeName = "dateCreated")
    public String getDateCreated() {return dateCreated;}
    public void setDateCreated(String dateCreated) {this.dateCreated = dateCreated;}

    @DynamoDBAttribute(attributeName = "dateIssued")
    public String getDateIssued() {return dateIssued;}
    public void setDateIssued(String dateIssued) {this.dateIssued = dateIssued;}

    @DynamoDBAttribute(attributeName = "rightsConsent")
    public String getRightsConsent() {return rightsConsent;}
    public void setRightsConsent(String rightsConsent) {this.rightsConsent = rightsConsent;}

    @DynamoDBAttribute(attributeName = "rightsRelease")
    public String getRightsRelease() {return rightsRelease;}
    public void setRightsRelease(String rightsRelease) {this.rightsRelease = rightsRelease;}

    @DynamoDBAttribute(attributeName = "contributorAuthor")
    public List<String> getContributorAuthor() {return contributorAuthor;}
    public void setContributorAuthor(List<String> contributorAuthor) {this.contributorAuthor = contributorAuthor;}

    @DynamoDBAttribute(attributeName = "contributorInterviewer")
    public List<String> getContributorInterviewer() {return contributorInterviewer;    }
    public void setContributorInterviewer(List<String> contributorInterviewer) {this.contributorInterviewer = contributorInterviewer;}

    @DynamoDBAttribute(attributeName = "creatorGender")
    public List<String> getCreatorGender() {return creatorGender;}
    public void setCreatorGender(List<String> creatorGender) {this.creatorGender = creatorGender;}

    @DynamoDBAttribute(attributeName = "creatorRaceEthnicity")
    public List<String> getCreatorRaceEthnicity() {return creatorRaceEthnicity;}
    public void setCreatorRaceEthnicity(List<String> creatorRaceEthnicity) {this.creatorRaceEthnicity = creatorRaceEthnicity;}

    @DynamoDBAttribute(attributeName = "creatorClass")
    public List<String> getCreatorClass() {return creatorClass;}
    public void setCreatorClass(List<String> creatorClass) {this.creatorClass = creatorClass;}

    @DynamoDBAttribute(attributeName = "creatorYearOfBirth")
    public List<String> getCreatorYearOfBirth() {return creatorYearOfBirth;}
    public void setCreatorYearOfBirth(List<String> creatorYearOfBirth) {this.creatorYearOfBirth = creatorYearOfBirth;}

    @DynamoDBAttribute(attributeName = "coverageSpatial")
    public List<String> getCoverageSpatial() {return coverageSpatial;}
    public void setCoverageSpatial(List<String> coverageSpatial) {this.coverageSpatial = coverageSpatial;}

    @DynamoDBAttribute(attributeName = "coveragePeriod")
    public List<String> getCoveragePeriod() {return coveragePeriod;}
    public void setCoveragePeriod(List<String> coveragePeriod) {this.coveragePeriod = coveragePeriod;}

    @DynamoDBAttribute(attributeName = "coverageRegion")
    public List<String> getCoverageRegion() {return coverageRegion;}
    public void setCoverageRegion(List<String> coverageRegion) {this.coverageRegion = coverageRegion;}

    @DynamoDBAttribute(attributeName = "coverageStateProvince")
    public List<String> getCoverageStateProvince() {return coverageStateProvince;}
    public void setCoverageStateProvince(List<String> coverageStateProvince) {this.coverageStateProvince = coverageStateProvince;}

    @DynamoDBAttribute(attributeName = "coverageNationality")
    public List<String> getCoverageNationality() {return coverageNationality;}
    public void setCoverageNationality(List<String> coverageNationality) {this.coverageNationality = coverageNationality;}

    @DynamoDBAttribute(attributeName = "language")
    public List<String> getLanguage() {return language;}
    public void setLanguage(List<String> language) {this.language = language;}

    @DynamoDBAttribute(attributeName = "subject")
    public List<String> getSubject() {return subject;}
    public void setSubject(List<String> subject) {this.subject = subject;}

    @DynamoDBAttribute(attributeName = "assetList")
    public List<HashMap<String, String>> getAssetList() {return assetList;}
    public void setAssetList(List<HashMap<String, String>> assetList) {this.assetList = assetList;
    }
}

